import gradio as gr
from duckduckgo_search import DDGS
import trafilatura
from transformers import pipeline
import torch
# from textblob import TextBlob  # Uncomment if autocorrection is needed

# Initialize the summarizer (CPU only)
summarizer = pipeline(
    "summarization",
        model="knkarthick/MEETING_SUMMARY",
            device=-1  # CPU to avoid CUDA issues
            )

            # Define output styles
            STYLE_PROMPTS = {
                "Formal business summary": "Summarize in a formal, business-like tone.",
                    "Casual conversation": "Summarize in a friendly, casual style.",
                        "Quick bullet points": "Summarize in short, concise bullet points.",
                        }

                        # Optional autocorrect function (requires TextBlob)
                        # def autocorrect(text):
                        #     return str(TextBlob(text).correct())

                        # Search news URLs using DuckDuckGo
                        def get_news_urls(query, max_results=5):
                            with DDGS() as ddgs:
                                    results = ddgs.news(query, max_results=max_results)
                                            return [r["url"] for r in results if "url" in r]

                                            # Extract main article content
                                            def extract_article_text(url):
                                                downloaded = trafilatura.fetch_url(url)
                                                    return trafilatura.extract(downloaded) if downloaded else None

                                                    # Main chatbot function
                                                    def chatbot_with_style(user_message, chat_history, style_choice):
                                                        if chat_history is None:
                                                                chat_history = []

                                                                    greetings = ["hi", "hello", "hey"]
                                                                        if user_message.lower().strip() in greetings:
                                                                                bot_reply = "👋 Hello! Ask me about any company or topic to get live news summaries."
                                                                                        chat_history.append((user_message, bot_reply))
                                                                                                return chat_history, ""

                                                                                                    if not user_message or len(user_message.strip()) < 3:
                                                                                                            bot_reply = "❓ Please enter a valid company or topic!"
                                                                                                                    chat_history.append((user_message, bot_reply))
                                                                                                                            return chat_history, ""

                                                                                                                                # user_message = autocorrect(user_message)  # Enable this line if autocorrection is used

                                                                                                                                    urls = get_news_urls(user_message)
                                                                                                                                        if not urls:
                                                                                                                                                bot_reply = f"⚠ Couldn't find news results for '{user_message}'. Try another topic."
                                                                                                                                                        chat_history.append((user_message, bot_reply))
                                                                                                                                                                return chat_history, ""

                                                                                                                                                                    summaries = []
                                                                                                                                                                        for url in urls:
                                                                                                                                                                                try:
                                                                                                                                                                                            article_text = extract_article_text(url)
                                                                                                                                                                                                        if not article_text or len(article_text.split()) < 100:
                                                                                                                                                                                                                        continue
                                                                                                                                                                                                                                    prompt = STYLE_PROMPTS.get(style_choice, "")
                                                                                                                                                                                                                                                summary_input = f"{prompt}\n\n{article_text}"
                                                                                                                                                                                                                                                            summary = summarizer(
                                                                                                                                                                                                                                                                            summary_input,
                                                                                                                                                                                                                                                                                            max_length=80,
                                                                                                                                                                                                                                                                                                            min_length=30,
                                                                                                                                                                                                                                                                                                                            do_sample=False
                                                                                                                                                                                                                                                                                                                                        )[0]["summary_text"]
                                                                                                                                                                                                                                                                                                                                                    summaries.append(f"- {summary.strip()} ([source]({url}))")
                                                                                                                                                                                                                                                                                                                                                            except Exception:
                                                                                                                                                                                                                                                                                                                                                                        continue

                                                                                                                                                                                                                                                                                                                                                                            if not summaries:
                                                                                                                                                                                                                                                                                                                                                                                    bot_reply = f"⚠ Couldn't generate good summaries for '{user_message}'."
                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                bot_reply = "Here are summaries from different articles:\n\n" + "\n\n".join(summaries)
                                                                                                                                                                                                                                                                                                                                                                                                        bot_reply += f"\n\n_Summarized from {len(summaries)} articles._"

                                                                                                                                                                                                                                                                                                                                                                                                            chat_history.append((user_message, bot_reply))
                                                                                                                                                                                                                                                                                                                                                                                                                return chat_history, ""

                                                                                                                                                                                                                                                                                                                                                                                                                # Gradio Interface
                                                                                                                                                                                                                                                                                                                                                                                                                with gr.Blocks() as demo:
                                                                                                                                                                                                                                                                                                                                                                                                                    gr.Markdown("## 🗞 News Summarizer Chatbot")

                                                                                                                                                                                                                                                                                                                                                                                                                        chatbox = gr.Chatbot(elem_id="chatbot")

                                                                                                                                                                                                                                                                                                                                                                                                                            with gr.Row():
                                                                                                                                                                                                                                                                                                                                                                                                                                    txt = gr.Textbox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                show_label=False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Type a company or topic, e.g. 'Google'...",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        container=False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style = gr.Radio(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    choices=list(STYLE_PROMPTS.keys()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value="Formal business summary",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label="Select output style",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        interactive=True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    container=False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    submit_btn = gr.Button("Send")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def user_submit(message, history, style_choice):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return chatbot_with_style(message, history, style_choice)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    submit_btn.click(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fn=user_submit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    inputs=[txt, chatbox, style],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            outputs=[chatbox, txt],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    txt.submit(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fn=user_submit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    inputs=[txt, chatbox, style],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            outputs=[chatbox, txt],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Launch the app
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                demo.launch(debug=True, share=True)